typography_spectrum: 0.31888359436239716
color:
  brandStrength: 0.5314239161547347
  lightness: 0.04374367844894307
  saturation: 0.2880112362704655
  rhythmicContrast: 0.9310134312969698
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
github: true
layout_spectrum: 0.6891197025630218
author:
  name: LG Larsen
  email: deemiinovo@gmail.com
  url: 'https://thegrid.ai/ourfriends/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/64124535-be79-424a-bee2-cd47bb7a0540.jpg
name: 'OurFriends '
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: CONTACT
    id: 50e32642-60da-4153-873b-ec625c75cd65
    type: content
  - name: Videos
    id: 5a9e3940-2b48-41c7-935a-f0771961a0d4
    type: content
  - name: Landscape
    id: 2df3cce8-d42c-4da3-bfd0-8b524ec432ab
    type: content
  - name: Sky
    id: 1b88bec6-efc8-40d8-abe3-e9530d3a7548
    type: content
  - name: 'Water '
    id: 9380d6fa-10ee-42e7-a464-f8b86577ad8d
    type: content
  - name: Pets
    id: c4efc5da-54d9-479f-b363-062235c793dd
    type: content
  - name: Places
    id: 80a8e44a-0694-4a1c-9cf7-1302fe9d99ad
    type: content
  - name: DeeMiiNovo
    id: 6aaaacf3-5b93-4c56-908d-3c9385f67f30
    type: content
  - name: LGsamiCrafts & Mii
    url: 'https://thegrid.ai/lgsamicrafts/'
    type: external
  - name: LGsignD & Dee
    url: 'https://thegrid.ai/lgsignd/'
    type: external
  - name: LG Larsen
    url: 'https://thegrid.ai/lg-larsen/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/70e9d71b-20a0-4a33-8293-c803b431ce23.jpg
title: OurFriends
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0397bd98-6be6-4998-9f46-b3313304ab3c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0397bd98-6be6-4998-9f46-b3313304ab3c.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Life around us
purpose:
  - type: internal
    label: VIDEOS
    item: 5a9e3940-2b48-41c7-935a-f0771961a0d4
